#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SERVER_PORT 5000
#define MAX_CLIENTS 4

#define TICK_RATE 60
#define TICK_DELAY_MS (1000 / TICK_RATE)

#define PHASE_1_DURATION_SEC 30.0f
#define PHASE_2_DURATION_SEC 180.0f
#define GHOST_TIMEOUT_SEC 15.0f

#define MAP_WIDTH 40
#define MAP_HEIGHT 30
#define TILE_SIZE 32.0f

#define PLAYER_WIDTH 20
#define PLAYER_LENGTH 30
#define DRAIN_RATE 20.0f
#define MAX_STAMINA 100.0f

#endif
